apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot-platform.fullname" . }}-env
data:
  TENANT_SERVICE_URL: {{ .Values.env.TENANT_SERVICE_URL }}
  ORCHESTRATOR_URL: {{ .Values.env.ORCHESTRATOR_URL }}
